/**
 * This file is for the Fall 2026 CSE 498 section 2 Capstone project.
 * @brief Represents the Interactive World module
 * @note Status: PROPOSAL
 **/

#pragma once

#include "../../core/WorldBase.hpp"
#include "Building.hpp"
#include "InteractiveWorldInventory.hpp"
#include "ResourceProducer.hpp"

#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>

namespace cse498 {

/**
 * World object for the interactive world
 */
class InteractiveWorld : public WorldBase {
public:
  enum class PlayerMove { Up, Down, Left, Right };

protected:
  enum ActionType {
    REMAIN_STILL = 0,
    MOVE_UP,
    MOVE_DOWN,
    MOVE_LEFT,
    MOVE_RIGHT,
    INTERACT
  };

  struct BuildingState {
    std::shared_ptr<Building> building{};
    std::shared_ptr<ResourceProducer> producer{};
    size_t tile_id{0};
  };

  InteractiveWorldInventory m_inventory;

  size_t grass_id{0};
  size_t grass_flowers_id{0};
  size_t grass_bones_id{0};
  size_t grass_mud_id{0};
  size_t grass_rock_id{0};
  size_t entrance_id{0};
  size_t wall_left_id{0};
  size_t wall_right_id{0};
  size_t wall_top_id{0};
  size_t wall_bottom_id{0};
  size_t wall_corner_id{0};
  size_t lumber_yard_id{0};
  size_t quarry_id{0};
  size_t ore_mine_id{0};

  WorldPosition mPlayerPosition{1, 1};
  std::string mPlayerSpriteName{"player"};
  std::string mAgentSpriteName{"skeleton"};
  std::string mLastActionMessage{};
  std::string mLastInventorySnapshot{};

  std::vector<BuildingState> m_buildings{};
  std::vector<std::shared_ptr<ResourceProducer>> m_producers{};

  /// Provide the agent with movement actions.
  void ConfigAgent(AgentBase &agent) override;

  /// Update world logic
  void UpdateWorld() override;

private:
  void BuildDefaultRoom();
  void BuildGuiTerrain();
  void SetupGuiBuildings();
  void PrintInventoryIfChanged(bool force = false);
  void SetActionMessage(std::string message, bool print_to_console = true);

  [[nodiscard]] bool IsBlockedTile(const WorldPosition &position) const;
  [[nodiscard]] bool IsBuildingAt(const WorldPosition &position) const;
  [[nodiscard]] bool IsPlayerAt(const WorldPosition &position) const;
  [[nodiscard]] bool IsAgentAt(const WorldPosition &position,
                               const AgentBase *ignore = nullptr) const;
  [[nodiscard]] std::optional<size_t>
  FindBuildingIndexAt(const WorldPosition &position) const;
  [[nodiscard]] std::optional<size_t> FindAdjacentBuildingIndex() const;
  bool TryUpgradeBuilding(size_t building_index);

public:
  InteractiveWorld();
  ~InteractiveWorld() override = default;

  /**
   * Rebuild the world into the SDL GUI hub layout.
   */
  void LoadGuiLayout();

  /**
   * Run producer/resource updates in the GUI loop.
   */
  void AdvanceSimulation();

  /**
   * Get the world inventory object
   * @return reference to world inventory
   */
  InteractiveWorldInventory &GetInventory() { return m_inventory; }
  const InteractiveWorldInventory &GetInventory() const { return m_inventory; }

  /**
   * Move the GUI-controlled player one tile if the destination is valid.
   */
  bool TryMovePlayer(PlayerMove move);

  /**
   * Interact with an adjacent building.
   */
  bool Interact();

  /**
   * Get the current GUI player position.
   */
  [[nodiscard]] WorldPosition GetPlayerPosition() const {
    return mPlayerPosition;
  }

  /**
   * Get the sprite key used to draw the player in the SDL GUI.
   */
  [[nodiscard]] const std::string &GetPlayerSpriteName() const {
    return mPlayerSpriteName;
  }

  /**
   * Get the sprite key used for any ambient agents rendered by the SDL GUI.
   */
  [[nodiscard]] const std::string &GetAgentSpriteName() const {
    return mAgentSpriteName;
  }

  /**
   * Last world action message generated by interaction or movement rules.
   */
  [[nodiscard]] const std::string &GetLastActionMessage() const {
    return mLastActionMessage;
  }

  /**
   * Check if a position is walkable for the player or world agents.
   */
  [[nodiscard]] bool IsWalkable(const WorldPosition &position) const;

  /**
   * Have agent perform an action
   * @param agent Agent to perform action on
   * @param action_id type of action to perform
   */
  int DoAction(AgentBase &agent, size_t action_id) override;

  /**
   * Overlay symbols on screen for text-mode interfaces.
   */
  std::vector<std::pair<WorldPosition, char>> GetOverlaySymbols() const;

  /**
   * Add producer to the world
   * @param producer producer to add
   */
  void AddProducer(std::shared_ptr<ResourceProducer> producer);

  /**
   * Add a building to the world at a given position
   * @param building building to add
   * @param position position to place building at
   * @param tile_id optional world tile used to render the building in GUI paths
   */
  void AddBuilding(std::shared_ptr<Building> building, WorldPosition position,
                   size_t tile_id = 0);
};

} // namespace cse498
